project:
  type: website
  title: "The Data Science Toolbox"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome to The Data Science Toolbox!**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
      - section: "**M8. Jupyter Book**"
        contents:
          - href: modules/module8/module8-00-module_learning_outcomes.qmd
          - href: modules/module8/module8-01-create_your_first_jupyter_book.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module8/module8-02-practice_today_a_reader_tomorrow_a_leader.qmd
          - href: modules/module8/module8-03-add_your_own_content:_essentials.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module8/module8-04-practice_becoming_an_author.qmd
          - href: modules/module8/module8-05-add_your_own_content:_advanced_features.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module8/module8-06-practice_do_it_like_a_professional.qmd
          - href: modules/module8/module8-07-publish_your_book_online.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module8/module8-08-practice_publication_ready.qmd
          - href: modules/module8/module8-09-what_did_we_just_learn.qmd
      - section: "**Module Closing Remarks**"
        contents:
          - href: modules/module9/module9-00-congratulations.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#122baf'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#122baf'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true