---
format: html
---

<script src='../../src/quiz.js'></script>

# 3.1. Exercises

## ✍️ Practice: Refine your shell skills

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'How do you view the first few lines of a file called <code>notes.txt</code>?',
        {
        '<code>cd notes.txt</code>': '<code>cd</code> is for changing to another directory.',
        '<code>head notes.txt</code>': '',
        '<code>tail notes.txt</code>': 'That would show the last few lines of the file, not the first few.',
        },
        '<code>head notes.txt</code>',
    );
</script>

<div id='mcq2'></div>
<script>
    generateQuiz(
        'mcq2',
        'Question 2',
        'How would you move the file <code>agenda.txt</code> from the parent directory <code>Documents</code> to your current directory <code>meeting-notes</code>?',
        {
        '<code>mv ./agenda.txt ..</code>': 'This command would move a file from the current directory to the parent directory.',
        '<code>mv ../agenda.txt .</code>': '',
        '<code>mv Documents/agenda.txt .</code>': 'This command would move a file from a directory called <code>Documents</code> that is under the current directory. The parent directory is above the current directory.',
        },
        '<code>mv ../agenda.txt .</code>',
    );
</script>

<div id='mcq3'></div>
<script>
    generateQuiz(
        'mcq3',
        'Question 3',
        'Which of the following files would be removed if we type <code>rm not*</code>?',
        {
        '<code>no.txt</code>': 'The file needs to start with <code>not</code>.',
        '<code>notes.txt</code>': '',
        '<code>my-note.txt</code>': 'The file needs to start with <code>not</code>.',
        },
        '<code>notes.txt</code>',
    );
</script>
