---
format: html
---

<script src='../../src/quiz.js'></script>

# 1.1. Exercises

## ✍️ Practice: Be careful if you can't see the forest because of all the branches

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'Which of these names are used to refer to the default branch in Git/GitHub?',
        {
        '<code>HEAD</code>': '<code>HEAD</code> is providing valuable information to the user when checking the project history. Specifically, it will point to the commit that you are currently at in the repository.',
        '<code>main</code>': 'Right, but there is also another correct option.',
        '<code>origin</code>': '<code>origin</code> is referring to the remote GitHub repository.',
        '<code>master</code>': 'Right, but there is also another correct option.',
        'The three first options are all correct': '<code>main</code>, <code>origin</code> and <code>HEAD</code> are labels that provide valuable information to the user when checking the project history, but two of them not necessarily refer to the default branch.',
        '<code>main</code> and <code>master</code>': '<code>master</code> was the old name for the default branch and <code>main</code> is the new one. You still will find repositories that use <code>master</code> to refer to the default branch.',
        '<code>origin</code> and <code>master</code>': 'Only one of these options is correct.',
        },
        '<code>main</code> and <code>master</code>',
    );
</script>

<div id='mcq2'></div>
<script>
    generateQuiz(
        'mcq2',
        'Question 2',
        'When should you create a new branch?',
        {
        'When you want to make a change that can break the code in the <code>main</code> branch': 'Right, but there is also another correct option.',
        'You can create a branch when you decide to add a new feature, even if you later decide not to merge it': 'Right, but there is also another correct option.',
        'You can create a branch to fix a bug, and then merge it to <code>main</code>': 'Right, but there is also another correct option.',
        'It is the first thing you should do after you start a project. You open a branch for all the features you are planning to add to your code': 'You cannot predict when you will need to fix a bug.',
        'All options are correct': 'Remember that you create a branch based on the current state of your project. Are you sure it makes sense to create all of them at the beginning of the project?',
        'The first three options are all correct': '',
        },
        'The first three options are all correct',
    );
</script>

<div id='mcq3'></div>
<script>
    generateQuiz(
        'mcq3',
        'Question 3',
        'Imagine that you cloned a repository from Github with a README file to your own computer. You then created a new local branch called <code>app</code> and made three commits. What labels will be included in your most recent commit (the third one) when you view the repo’s commit history?',
        {
        '<code>origin/HEAD</code> and <code>origin/main</code>': '<code>origin/HEAD</code> and <code>origin/main</code> point to the latest changes in the remote repository at the time of pulling.',
        '<code>HEAD -> app</code>': '<code>HEAD</code> points to the most recent branch where you made changes, which is the <code>app</code> branch.',
        '<code>main</code>': 'Which branch are you currently working on?',
        '<code>HEAD -> main</code>': 'Which branch are you currently working on?',
        },
        '<code>HEAD -> app</code>',
    );
</script>
