---
format: html
---

<script src='../../src/quiz.js'></script>

# 2.1. Exercises

## ✍️ Practice: Know your diffs

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'View this <code>git diff</code> comparison on GitHub: <a href=https://github.com/UBC-MDS/equine_numbers_value_canada/compare/9021b83..1bb5ab8>https://github.com/UBC-MDS/equine_numbers_value_canada/compare/9021b83..1bb5ab8</a>. <br><br> You can see that changes have been made to the <code>README.md</code> file, highlighted in red (– signs) and green (+ signs) in the web interface. Based on the commit history and the order of the commits, which of these highlights, red or green, represent the current state of the <code>README.md</code> file in the repository?',
        {
        'Red': 'Correct! If you go to the current state of <a href=https://github.com/UBC-MDS/equine_numbers_value_canada/>the repository</a> and check the <code>README.md</code> file or the commit history, you can see that the file with red highlights represents the current state. You cannot rely solely on colors to determine which commit is newer.',
        'Green': 'Be careful with the colors, as they don’t always indicate which version is newer. The meaning of the highlights depends on the direction of the commit comparison. Try reversing the order of the commits to <code>1bb5ab8..9021b83</code> and you’ll see how the red and green highlights change',
        },
        'Red',
    );
</script>

<div id='mcq2'></div>
<script>
    generateQuiz(
        'mcq2',
        'Question 2',
        'How could you make a comparison between <code>1bb5ab8</code> and <code>9021b83</code> using <code>git diff</code> from the command line?',
        {
        '<code>git diff 9021b83</code>': '<code>9021b83</code> is the hash of the last commit, what would you like to compare it with?',
        '<code>git diff 1bb5ab8</code>': 'That’s right, but there is also another correct option!',
        '<code>git diff 1bb5ab8 9021b83</code>': 'That’s right, but there is also another correct option!',
        'The first and third options are both correct': 'In the first option, <code>9021b83</code> is the hash of the last commit, what would you like to compare it with?',
        'The second and third option are both correct': 'Writing the newest commit is not necessary. If you write only one commit (that is not the newest one) it will compare it with the last one without specifying anything else.',
        },
        'The second and third option are both correct',
    );
</script>
